### ISSUE TITLE
Wont compile

### ISSUE THREAD

**Issue by ata-star** [firoorg/cpuminer#27]
see screenshot for error message
![yes-i-completly-understand](https://user-images.githubusercontent.com/62115669/122356719-58900200-cf53-11eb-8568-522552c9155e.png)

**Comment by djm34** [comment]
what machine/OS are you using ?

**Comment by ata-star** [comment]
got it working im to dumb, but now i have another error, will close

**Comment by djm34** [comment]
well if it is the only level of detail... there isn't much point in opening an other issue regarding the "error" D (we don't practice divination)
